name: Code Review status
on:
  pull_request:
    types: [opened]
jobs:
  code-review-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo logs
        run: echo "state - ${{ github.event.review.state }} --- branch - ${{ toJson(github.head_ref) }} - action - ${{ toJson(github.event.action) }}"
