name: Test action

on:
  workflow_dispatch:
    inputs:
      runner-name:
        type: string
        required: false
        default: ("self-hosted" "ubuntu-self-prod")

env:
  DEFAULT_RUNNER: ("self-hosted" "ubuntu-self-prod")
  
jobs:
  print-value-from-input:
    runs-on: ["${{ inputs.runner-name }}"]
    steps:
      - name: Print the input name to STDOUT
        run: echo Runner name is ${{ inputs.runner-name }} and $DEFAULT_RUNNER
