name: Deploy To Some Server

on:
  workflow_dispatch:
    inputs:
      dev:
        required: true
        description: dev name (optimus/starscream/thunderwing/mirage/bumblebee)

jobs:
  deploy-to-dev:
    environment: ${{ github.event.inputs.dev }}
    runs-on: ubuntu-latest
    steps:
      - name: export my something
        id: export
        run: |
          echo "GITHUB_SHA_CURRENT_BRANCH=$(git rev-parse HEAD)" >> $GITHUB_ENV
