name: Test action

on:
  workflow_dispatch:
    inputs:
      runner-name:
        type: string
        required: false

jobs:
  print-value-from-input:
    runs-on: ${{ inputs.runner-name || fromJson( '["self-hosted", "ubuntu-self-prod"]' ) }}
    steps:
      - name: Print the input name to STDOUT
        run: echo Runner name is ${{ inputs.runner-name }}
