name: Ready for Test status
on:
  pull_request_review:
    types: [submitted]
jobs:
  ready-for-test-job:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - name: Check if PL has 2 approvals
        uses: luisrjaeger/approved-event-checker@master
        id: approved
        with:
          approvals: 2
          check_changes_requested: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug
        run:  echo "approvved - ${{ steps.approved.outputs.approved }} --- "

      - name: Parse Jira ticket id
        if: steps.approved.outputs.approved == 'true'
        shell: bash
        id: ticket-id
        run: echo "##[set-output name=issue;]$(echo ${{ github.event.pull_request.head.ref }} | grep -oP '^ALDEV-\d+')"

      - name: Login to Jira
        if: steps.approved.outputs.approved == 'true'
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Debug 2
        run:  echo "s - ${{ steps.ticket-id.outputs.issue }} --- "

      - name: Debug 3
        run:  echo "s - contains(${{ steps.ticket-id.outputs.issue }}, 'ALDEV') --- "

      - name: Move to Merged status
        if: steps.approved.outputs.approved == 'true' && contains(${{ steps.ticket-id.outputs.issue }}, 'ALDEV')
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.ticket-id.outputs.issue }}
          transition: "DONE" # her1e will be Merged
