name: Test on Pull_request
on:
  pull_request:
jobs:
  test-on-pull-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo github
        run: echo "state - ${{ toJson(github) }} " # no mergable properties

      - name: Echo mergable
        run: echo "${{ toJson(github.event.pull_request.mergeable) }} ---  ${{ toJson(github.event.pull_request.mergeable_state) }} --- ${{ toJson(github.event.pull_request.merge_commit_sha) }}"
